import type { HelpEntry } from "./types";

export const bodyHelp = {
  exercise: {
    title: "Exercise",
    purpose: `This page is your training log. You record gym sessions, runs, walks, swims and other activities here, keep reusable gym programs, and track your body weight and body measurements.`,
    steps: [
      `Pick an activity type in the "Log activity" card: "Gym", "Run", "Walk", "Swim" or "Other".`,
      `Fill in the fields for that type and press the log button, for example "Log run" or "Create & add exercises".`,
      `Open a workout in "Recent workouts" to see its details or, for a gym session, to add exercises and sets.`,
      `Create a program with "New program" if you repeat the same gym session, then press "Start workout" on it each time you train.`,
      `Record your weight in "Body weight" and sizes such as waist in "Body measurements" with the "Log" buttons.`,
    ],
    capabilities: [
      `Log a gym session with "Session name", "Date" and optional "Notes". "Create & add exercises" saves it and opens the workout so you can add exercises and sets.`,
      `Log a run with "Distance (km)", "Duration (min)", "Date" and optional "Notes". The run is named for you from the distance, for example "Run 5 km".`,
      `Log a walk with "Type" ("Outdoor" or "Indoor"), "Duration (min)", an optional "Distance (km)", "Date" and optional "Notes".`,
      `Log a swim with "Distance (m)", "Duration (min)", "Date" and optional "Notes".`,
      `Log any other activity, such as yoga, with "Activity" (required), "Duration (min)" and "Date".`,
      `Start a gym session from a saved program with "Start workout". It creates a workout dated today, named after the program, with the program's exercises and planned sets already in it, and opens it.`,
      `Create programs with "New program", or go straight to the text import with "Paste from text".`,
      `Open a program by its name or "Edit", and expand "Exercises" on a program card to see its exercise list without leaving the page.`,
      `Archive a program you no longer use with "Archive", see archived ones with "Show archived", and bring one back with "Restore".`,
      `Browse "Recent workouts", which shows each workout's type, date and a short summary. Select one to open it.`,
      `Delete a workout with the bin button on its row. You are asked to confirm first.`,
      `Log your weight with "Weight (kg)" and "Date". The header shows your latest weight and the change from the entry before it.`,
      `Log a body measurement with "Measurement" (for example waist), "cm" and "Date".`,
      `Delete a weight entry or a measurement with the bin button beside it.`,
    ],
    tips: [
      `"Start workout" only appears on active programs that have at least one exercise.`,
      `The page lists your 30 most recent workouts, 10 most recent weigh-ins and 10 most recent measurements. Older entries are not shown here.`,
      `If you have a goal set to auto-track "Workouts logged", every workout you log here adds 1 to it. Deleting a workout does not take that 1 back.`,
      `The activity type you chose last is remembered on this device, so the card opens on it next time. Programs cannot be deleted, only archived.`,
    ],
    related: [
      { label: "New program", href: "/dashboard/exercise/programs/new" },
      { label: "Settings", href: "/dashboard/settings" },
    ],
  },

  "exercise:workout": {
    title: "Exercise: Workout",
    purpose: `This page shows one logged workout. For a gym session it is where you add exercises and record each set as you train. For a run, walk, swim or other activity it shows the distance, duration and pace you logged.`,
    steps: [
      `Type an exercise name in "Add exercise" and press "Add" (skip this if the workout was started from a program).`,
      `Enter "Reps", "Weight (kg)" or "Time (s)" for the set you just did.`,
      `Press "Add set 1" to save it; the button moves on to "Add set 2" and so on.`,
      `Repeat for each set and each exercise until the session is done.`,
      `Use the "Exercise" link at the top to go back to your log.`,
    ],
    capabilities: [
      `See the workout's name, activity type and date, plus its notes if it has any.`,
      `For a workout started from a program, follow the "From" link under the title to open that program.`,
      `Add an exercise to a gym session with "Add exercise" and "Add". New exercises go to the bottom of the list.`,
      `Record a set with "Reps", "Weight (kg)" and "Time (s)". You need to fill in at least one of the three.`,
      `See the plan for exercises that came from a program, shown as "Planned" with sets and reps, and a progress badge such as "2 of 3 sets" that turns green when you reach the planned number.`,
      `Have the next set filled in for you: the form repeats the values of your last set, or starts with the planned reps when you have no sets yet.`,
      `Delete a single set with the bin button on its row.`,
      `Remove an exercise with the bin button beside its name. Its sets are deleted with it.`,
      `For a run, walk, swim or other activity, see "Distance" and "Duration". Runs and walks with both values also show "Average pace"; a walk without a pace shows its "Type" (Indoor or Outdoor).`,
      `Delete the whole workout with "Delete workout". After you confirm you are taken back to the Exercise page.`,
    ],
    tips: [
      `A saved set cannot be edited. To correct one, delete it and add it again.`,
      `The workout's name, date and notes cannot be changed here, and a run, walk, swim or other activity cannot be edited at all. Delete it and log it again if it is wrong.`,
      `You can log more sets than the plan asks for; the badge simply stays complete.`,
      `Changing or removing an exercise here does not change the program the workout came from.`,
    ],
    related: [{ label: "Exercise", href: "/dashboard/exercise" }],
  },

  "exercise:program-new": {
    title: "Exercise: New program",
    purpose: `This page creates a program, which is a reusable gym session such as Full Body. You can create an empty program and add exercises afterwards, or paste a written list of exercises and have the program built from it.`,
    steps: [
      `Decide whether to start empty or from a list you already have written down.`,
      `To start empty, enter a "Name" under "Create empty program" and press "Create program".`,
      `To use a list, paste it into "Program text" under "Paste from text", with the program name on the first line and one exercise per line.`,
      `Check the "Preview" and any warnings that appear below the text box.`,
      `Press "Save program" to create the program and open it.`,
    ],
    capabilities: [
      `Create an empty program with "Name" and optional "Notes". "Create program" opens the new program so you can add exercises.`,
      `Paste a whole program as text in "Program text" and have it turned into a program with its exercises.`,
      `Write an exercise with a set count, such as "1. Bench Press - 3 sets". The number at the start of the line is optional.`,
      `Write an exercise with sets and reps, such as "Bench Press 3x8" or "Bench Press - 3 sets x 8".`,
      `Write an exercise as a numbered line with no set count, such as "1. Squat". It is given 3 sets and a warning tells you so.`,
      `Name the program from the text: the first line that is not an exercise becomes the program name. If there is none, the program is called "Workout program".`,
      `See a live "Preview" of the program name and the numbered exercise list, updated as you type.`,
      `See a warning for each line that could not be read, with its line number. Those lines are left out of the program.`,
      `Save the result with the "Save program" button, which also shows how many exercises will be saved.`,
    ],
    tips: [
      `A line with only an exercise name, no number in front and no set count, is not read as an exercise. Add a number in front or a set count.`,
      `"Save program" only appears once at least one exercise has been found in the text.`,
      `A pasted program has no notes and no reps unless you wrote them. You can change the name, notes, sets and reps on the program page afterwards.`,
    ],
    related: [{ label: "Exercise", href: "/dashboard/exercise" }],
  },

  "exercise:program": {
    title: "Exercise: Program",
    purpose: `This page is where you edit one saved program: its name, its notes and its list of exercises with planned sets and reps. You can also start a workout from the program here.`,
    steps: [
      `Type an exercise name in "Add exercise", set "Sets" and optionally "Reps", then press "Add".`,
      `Repeat until the program holds every exercise in the session.`,
      `Use the up and down arrows under an exercise to put the list in the order you train.`,
      `Press "Start workout" at the top when you are ready to train.`,
    ],
    capabilities: [
      `Rename the program or change its "Notes", then press "Save program".`,
      `Add an exercise with "Add exercise", "Sets" and optional "Reps". "Sets" starts at 3.`,
      `Change an exercise's name, "Sets" or "Reps" in its row and press "Save" on that row.`,
      `Move an exercise up or down the list with the arrow buttons. The order here is the order the exercises appear in a workout.`,
      `Remove an exercise from the program with the bin button on its row.`,
      `Start a gym session with "Start workout". It creates a workout dated today with a copy of the exercises and their planned sets and reps, and opens it.`,
      `Hide the program from your active list with "Archive", or bring an archived program back with "Restore".`,
      `Jump to the text import with "Paste from text", shown while the program has no exercises.`,
    ],
    tips: [
      `Each exercise row has its own "Save" button. Changes you type in a row are not kept until you press it.`,
      `"Start workout" is hidden while the program is archived or has no exercises.`,
      `Editing or removing exercises here does not change workouts you already logged, because each workout keeps its own copy.`,
      `"Sets" and "Reps" must be whole numbers of 1 or more. A program cannot be deleted, only archived. "Paste from text" always creates a new program; it does not add to this one.`,
    ],
    related: [
      { label: "Exercise", href: "/dashboard/exercise" },
      { label: "New program", href: "/dashboard/exercise/programs/new" },
    ],
  },

  religious: {
    title: "Religious",
    purpose: `This page tracks your daily worship in one place: the five daily prayers, prayers you still need to make up (qaza), your Quran reading, a set of daily readings, dhikr (words of remembrance you repeat and count) and fasting. Four figures at the top summarise your on-time streak, pending qaza, dhikr today and your Quran page.`,
    steps: [
      `Mark each of today's prayers "On time" or "Missed" under "Prayers for today".`,
      `Press "Fulfill one" in "Daily qaza" whenever you make up a missed prayer.`,
      `Log your Quran reading with "+1 page", "+5 pages" or "+10 pages" in "Quran khatm".`,
      `Press "Add suggested readings" in "Daily readings", or add your own under "Manage readings", then tap "+1" as you read.`,
      `Enter a "Dhikr" name and "Count" and press "Log dhikr".`,
      `Record a fast with "Date" and "Kind" and press "Log fast".`,
    ],
    capabilities: [
      `Mark each of the five prayers (Fajr, Dhuhr, Asr, Maghrib, Isha) "On time" or "Missed". Each row saves as soon as you tap it.`,
      `Have missed prayers added to your qaza list for you. Switching a missed prayer to "On time", or clearing it with the x button, removes that qaza entry again as long as you have not fulfilled it.`,
      `Fill in every prayer that has no status yet with "Mark all on time" (it reads "Mark remaining" with a number when some are already set). Prayers you marked "Missed" stay missed.`,
      `Move to another day with the arrows beside the date, pick a date with the calendar button, or return with "Today". You cannot go past today.`,
      `Make up missed prayers in "Daily qaza": "Fulfill one" clears the oldest one for that prayer, or enter a number and press "Fulfill" to clear several, oldest first. "Show dates" lists the days they came from.`,
      `Record prayers you owe from before you started tracking under "Set up historical debt" (a count per prayer). Enter "Period start" and "Period end" to get an estimate of one of each prayer per day, press "Apply to all prayers", adjust the counts, add an optional "Note" and press "Save historical debt".`,
      `Work through historical debt with "Fulfill 1", or a number and "Fulfill", for each prayer. A bar shows how many are fulfilled and how many are left.`,
      `Change the owed counts later under "Update historical debt", or delete all of it with "Clear all historical debt".`,
      `Track a khatm (one full reading of the Quran, 604 pages) in "Quran khatm". Log pages with the quick buttons, or enter "Pages" and an optional "Note" and press "Log pages". The card shows your next page, juz, percentage and "Recent sessions".`,
      `Correct your place under "Set current page": set the next page and "Khatms completed", then press "Save position".`,
      `Keep a personal list of daily readings, each with a target per day in pages or times. Tap "+1" to log one, or the second button to log the full daily target at once. A reading shows "Done" when today's target is met.`,
      `Add, rename, retarget or remove readings under "Manage readings". "Add suggested readings" creates a starter set (Quran, Jawshan, Risale-i Nur, Gülen) when your list is empty.`,
      `Log dhikr with a name and a count, see everything under "Logged today", and set a daily target per dhikr under "Manage targets" with "Dhikr name", "Per day" and "Set target". Targets show a progress bar and "Done" when reached.`,
      `Log a fast with "Date", "Kind" ("Ramadan", "Voluntary" or "Make-up (qada)") and an optional "Note". "Recent fasts" shows your latest seven.`,
    ],
    tips: [
      `Only the prayers follow the day you pick. Dhikr, Quran pages and daily readings always log to today, and fasting has its own "Date" field.`,
      `The reading marked "Linked to khatm" and the Quran card move together: logging on either one advances your bookmark and counts toward that reading's daily target. Passing page 604 starts the next khatm and adds 1 to your completed count. Only the Quran reading from the suggested set is linked; one you add yourself is not.`,
      `Logged dhikr, Quran pages, reading amounts and fasts cannot be removed on this page. For Quran you can fix your place with "Set current page"; logging a fast again for the same date replaces its kind and note.`,
      `Setting a prayer to 0 in the historical debt form removes its debt, "Clear all historical debt" cannot be undone, and removing a reading deletes everything logged for it. If you have a goal set to auto-track "Quran pages read", each page you log is added to it.`,
    ],
    related: [{ label: "Settings", href: "/dashboard/settings" }],
  },

  migraine: {
    title: "Migraine",
    purpose: `This page is a migraine diary. You mark the days you had a migraine on a month calendar with a pain level from 1 to 10, and can add how long it lasted and a note. The figures at the top summarise the month you are looking at.`,
    steps: [
      `Tap the day you had a migraine on the calendar (today is selected when you open the page).`,
      `Tap a pain level from 1 to 10 under "Mild", "Moderate" or "Severe".`,
      `Open "More" and choose a "Duration" if you know how long it lasted.`,
      `Type anything worth remembering in "Note", such as triggers or what helped, and press "Save note".`,
    ],
    capabilities: [
      `Log a migraine day by tapping a pain level from 1 to 10. It saves straight away and the number appears on that day in the calendar.`,
      `Change the pain level of a day by tapping a different number.`,
      `Set how long it lasted under "More" with "<2h", "2–4h", "4–12h" or "All day".`,
      `Add or change a note of up to 2000 characters and save it with "Save note". Saving an empty note removes it.`,
      `Remove a day's entry completely with "Clear day". You are asked to confirm first.`,
      `Read the calendar at a glance: each logged day shows its pain number in a colour for "Mild 1–3", "Moderate 4–6" or "Severe 7–10".`,
      `Move between months with the arrows beside the month name, and return with "This month".`,
      `See "Migraine days", "Average pain" and "Severe days" (pain 7 to 10) for the month shown.`,
      `Tap a greyed day from the previous or next month to switch the calendar to that month and select the day.`,
    ],
    tips: [
      `"Duration" and "Note" stay locked until the day has a pain level.`,
      `Future days cannot be selected or logged.`,
      `There is no pain level 0. A day with no entry counts as no migraine, so use "Clear day" to undo an entry made by mistake. A duration can be changed but not removed on its own.`,
      `The note is only saved when you press "Save note"; pain and duration save as soon as you tap them. When you open another month no day is selected until you tap one.`,
    ],
    related: [{ label: "Settings", href: "/dashboard/settings" }],
  },
} satisfies Record<string, HelpEntry>;
